export const MetricActions = {
    REPLACE_METRICS_DATA: 'REPLACE_METRICS_DATA',
    REPLACE_REALTIME_METRICS_DATA: 'REPLACE_REALTIME_METRICS_DATA',
    SET_REPORT_DATA: 'SET_REPORT_DATA',
    SET_AGENTS_DATA: 'SET_AGENTS_DATA',
    SET_AGENT_STATUS_VISIBILITY: 'SET_AGENT_STATUS_VISIBILITY',
    SET_REALTIME_METRIC_VISIBILITY: 'SET_REALTIME_METRIC_VISIBILITY',
    SET_HISTORIC_METRIC_VISIBILITY: 'SET_HISTORIC_METRIC_VISIBILITY',
    SET_REPORT_VISIBILITY: 'SET_REPORT_VISIBILITY',
    SET_AGENTS_VISIBILITY: 'SET_AGENTS_VISIBILITY',
    SET_AGENT_STATUS_DATA: 'SET_AGENT_STATUS_DATA',
    SET_ATTRIBUTE_REPORT_VISIBILITY: 'SET_ATTRIBUTE_REPORT_VISIBILITY',
    SET_ATTRIBUTE_REPORT_DATA: 'SET_ATTRIBUTE_REPORT_DATA'
}

export const MetadataActions = {
    SET_INSTANCE_CONFIG: 'SET_INSTANCE_CONFIG',
    SET_API_CONFIG: 'SET_API_CONFIG',
    SET_APP_READY: 'SET_APP_READY',
    SET_ATTRIBUTE_TRACING: 'SET_ATTRIBUTE_TRACING'
}

export const QueueActions = {
    SET_QUEUE_VISIBILITY: 'SET_QUEUE_VISIBILITY',
    UPDATE_QUEUE_LIST: 'UPDATE_QUEUE_LIST'
}

export const AgentActions = {
    STORE_INFO: 'STORE_INFO'
}

export const ContactActions = {
    ADD_CONTACT: 'ADD_CONTACT'
}

export const ContactFlowsActions = {
    SET_CONTACT_FLOWS_LIST: 'SET_CONTACT_FLOWS_LIST',
    SET_CONTACT_FLOWS_LIST_VISIBILITY: 'SET_CONTACT_FLOWS_LIST_VISIBILITY',
    SET_CONTACT_FLOW_PROMPTS: 'SET_CONTACT_FLOW_PROMPTS',
    SET_CONTACT_FLOW_PROMPTS_VISIBILITY: 'SET_CONTACT_FLOW_PROMPTS_VISIBILITY'
}

export const ConnectPromptsActions = {
    SET_CONNECT_PROMPTS: 'SET_CONNECT_PROMPTS',
    SET_CONNECT_PROMPTS_VISIBILITY: 'SET_CONNECT_PROMPTS_VISIBILITY'
}